stages:
- name: build
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: |-
        echo building... version:${CICD_GIT_BRANCH}
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-X "main.version='"${CICD_GIT_BRANCH}"'"' -o example
- name: build-image
  steps:
  - publishImageConfig:
      dockerfilePath: ./dockerfile
      buildContext: .
      tag: j75689/${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}
      pushRemote: true
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./.deployment.yaml
    env:
      JAEGER_AGENT_HOST: jaeger-agent.istio-system:5775
timeout: 60
notification: {}
