stages:
- name: build
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o example
- name: build-image
  steps:
  - publishImageConfig:
      dockerfilePath: ./dockerfile
      buildContext: .
      tag: j75689/jaeger-tracing-example
      registry: https://registry.hub.docker.com
timeout: 60
notification: {}
